import Navbar from '../components/navbar'
import Footer from '../components/footer'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Box, Button, Center, Heading, HStack, Link, Stack, Text, Wrap, WrapItem } from '@chakra-ui/react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bat Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        {/* MAIN LANDING PAGE SECTION */}
        <div className="section" id="top">
          <Navbar />
          <Center bg="black" maxHeight="2160px" h="100vh" color="white">
            <Stack spacing={1}>
              <Heading as="h1" size="xl">
                Hi, I&apos;m Bat!<br></br>
                Software Developer
              </Heading>

              <HStack spacing={2}>
                <Link href="https://github.com/Baagi" isExternal> Github </Link>
                <Link href="https://www.linkedin.com/in/bat-battur-a9b1b8217" isExternal> LinkedIn </Link>
                <Link href="mailto:webmaster@example.com" isExternal> Email</Link>
                <Button colorScheme="transparent"> Download Resume</Button>
              </HStack>

              <Heading as="h1" size="4xl">
                Welcome to my site!
              </Heading>
            </Stack>
          </Center>
        </div>

        {/* ABOUT ME SECTION */}
        <div className="section">
          <Center bg="linear-gradient(170deg, white, #F7F7F7)" maxHeight="2160px" h="100vh" w="100vw" color="black" id="about">
            <Stack spacing={6}>
              <Heading as="h1" size="2xl">
                About Me
              </Heading>

              <Text as="h1" size="xl">
                I&apos;m currently a 4th year Software Engineering student at Cal Poly, San Luis Obispo.
                <br></br> I&apos;m also a Software QA apprentice at an awesome right-to-repair company called iFixit.
                <br></br>
                I love writing code and building new things.
              </Text>

              <HStack spacing={10}>
                <Wrap >
                  <WrapItem>
                    <Stack>
                      <Heading as="h1" size="xl">
                        Education
                      </Heading>
                      <Text as="h1" size="xl">
                        California Polytechnic State University
                        <br></br>
                        B.S.Software Engineering
                        <br></br>
                        San Luis Obispo, CA
                        <br></br>
                        Expected Graduation: June 2022
                      </Text>
                    </Stack>
                  </WrapItem>
                  <WrapItem>
                    <Stack>
                      <Heading as="h1" size="xl">
                        Experience
                      </Heading>
                      <Text as="h1" size="xl">
                        Software QA 💼 <Link to='https://www.ifixit.com/' isExternal >iFixit </Link>
                        <br></br>
                        San Luis Obispo, CA
                        <br></br>
                        Dec 2018 - Present
                      </Text>
                    </Stack>
                  </WrapItem>
                </Wrap >
              </HStack>
            </Stack>
          </Center>
        </div>

        {/* WEB DEV SECTION */}
        <div className="section">
          <Center bg="linear-gradient(170deg, #05C4EE, #2B6CB0)" maxHeight="2160px" h="100vh" w="100vw" color="white" id="development">

            <Stack spacing={1}>
              <Heading as="h1" size="2xl">
                Development
              </Heading>

              <HStack spacing={2} direction={["row", "column"]}>
                <Wrap >
                  <WrapItem>
                    <Stack spacing={1}>
                      <Text fontSize="2xl" fontWeight="bold">
                        Services
                      </Text>
                      <Text>
                        Best solutions to your creative project.
                        <br></br>
                        Do you need a vibrant new website that <br></br>
                        runs smoothly?Then you found the right <br></br>
                        person!
                      </Text>
                    </Stack>
                  </WrapItem>

                  <WrapItem >
                    <Stack spacing={4} margin="0 10px">
                      <Text fontSize="xl">
                        Web Development
                      </Text>
                      <Text fontSize="xl">
                        UX/UI design
                      </Text>
                    </Stack>

                    <Stack spacing={4}>
                      <Text fontSize="xl">
                        Project Management
                      </Text>
                      <Text fontSize="xl">
                        Quality Assurance
                      </Text>
                    </Stack>
                  </WrapItem>
                </Wrap>
              </HStack>
              <Text fontSize="2xl">
                <Link href="#contact">Contact Me </Link>
              </Text>

              <Heading as="h1" size="2xl">
                Techonologies
              </Heading>

              <HStack spacing={2}>
                <Text fontSize="2xl">
                  Front-end
                </Text>
                <Text fontSize="2xl">
                  Backend
                </Text>
                <Text fontSize="2xl">
                  Database
                </Text>
                <Text fontSize="2xl">
                  Tools
                </Text>
              </HStack>

            </Stack>
          </Center>
        </div>

        {/* PROJECTS SECTION */}
        <div className="section">
          {/* "linear-gradient(170deg, #00DA9E, #319795)" */}
          <Center bg="linear-gradient(150deg, #E4CD82, #FD61C7)" maxHeight="2160px" h="100vh" w="100vw" id="projects" color="white">

            <Stack>
              <Heading as="h1" size="xl">
                Projects
              </Heading>

              <Heading as="h1" size="xl">
                Project Name
                <br></br>
                Project Description
                <br></br>
                More info / View Project
                <br></br>
                Tech stack:
              </Heading>
            </Stack>
          </Center>
        </div>

        {/* GET IN TOUCH SECTION */}
        <div className="section">
          <Box bg="linear-gradient(240deg, #7C00E4, purple)" maxHeight="2160px" h="100vh" color="white" id="contact">

            <Center maxHeight="2160px" h="95vh" color="white" id="contact">
              <Stack>
                <Heading as="h1" size="2xl">
                  Get In Touch
                </Heading>

                <HStack spacing={2} justifyContent="center" fontSize="xl">
                  <Link href="mailto:webmaster@example.com" isExternal> Email </Link>
                  <Link href="https://www.linkedin.com/in/bat-battur-a9b1b8217" isExternal> LinkedIn </Link>
                  <Link href="https://github.com/Baagi" isExternal> Github </Link>
                </HStack>
              </Stack>
            </Center>
            <Footer justifyContent="center" />
          </Box>
        </div>
      </main >

    </div >
  )
}
