import Head from 'next/head'
import { Box, Button, Center, Heading, HStack, Link, Stack, Text, Wrap, WrapItem } from '@chakra-ui/react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bat Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        {/* MAIN LANDING PAGE SECTION */}
        <div className="section" id="top">
          {/* <Navbar /> */}
          <Center bg="black" maxHeight="2160px" h="100vh" color="white">
            <Stack spacing={1}>
              <Heading as="h1" size="xl">
                Hi, I&apos;m Bat!<br></br>
                Software Developer
              </Heading>

              <HStack spacing={2}>
                <Link href="https://github.com/Baagi" isExternal> Github </Link>
                <Link href="https://www.linkedin.com/in/bat-battur-a9b1b8217" isExternal> LinkedIn </Link>
                <Link href="mailto:bbattur@calpoly.edu" isExternal> Email</Link>
                <a href='/resume.pdf' download>Download Resume</a>

              </HStack>

              <Heading as="h1" size="4xl">
                Welcome to my site!
              </Heading>
            </Stack>
          </Center>
        </div>

        {/* ABOUT ME SECTION */}
        <div className="section">
          <Center bg="linear-gradient(170deg, white, #F7F7F7)" maxHeight="2160px" h="100vh" w="100vw" color="black" id="about">
            <Stack spacing={6}>
              <Heading as="h1" size="2xl">
                About Me
              </Heading>

              <Text as="h1" size="xl">
                I&apos;m currently a 4th year Software Engineering student at Cal Poly, San Luis Obispo.
                <br></br> I&apos;m also a Software QA apprentice at iFixit, extra cool repair company. 
                <br></br>
                I love writing code and passionate for building new things.
              </Text>

              <HStack spacing={10}>
                <Wrap >
                  <WrapItem>
                    <Stack>
                      <Heading as="h1" size="xl">
                        Education
                      </Heading>
                      <Text as="h1" size="xl">
                        California Polytechnic State University
                        <br></br>
                        B.S.Software Engineering
                        <br></br>
                        San Luis Obispo, CA
                        <br></br>
                        Expected Graduation: June 2022
                      </Text>
                    </Stack>
                  </WrapItem>
                  <WrapItem>
                    <Stack>
                      <Heading as="h1" size="xl">
                        Experience
                      </Heading>
                      <Text as="h1" size="xl">
                        Software QA 💼 <Link to='https://www.ifixit.com/' isExternal >iFixit </Link>
                        <br></br>
                        San Luis Obispo, CA
                        <br></br>
                        Dec 2018 - Present
                      </Text>
                    </Stack>
                  </WrapItem>
                </Wrap >
              </HStack>
            </Stack>
          </Center>
        </div>

        {/* WEB DEV SECTION */}
        <div className="section">
          <Center bg="linear-gradient(170deg, #05C4EE, #2B6CB0)" maxHeight="2160px" h="100vh" w="100vw" color="white" id="development">

            <Stack spacing={3}>
              <Heading as="h1" size="2xl">
                Projects
              </Heading>

              <Stack spacing={3}>
                <Text fontSize="xl">
                  SLO Hikes, Web app for hikers: <Link href='https://slohikes.herokuapp.com/' isExternal color="darkblue">click here ↗ </Link>
                </Text>
                <Text fontSize="l">
                  Web app developed for a group project for Software Engineering I and II classes.
                  <br></br>
                  Used MongoDB, Express, React, and NodeJS (MERN) stack to develop all of the features.
                  <br></br>
                  Applied all software development practices in the process.
                </Text>
              </Stack>

              <Heading as="h1" size="xl">
                Skills/Technologies
              </Heading>

              <Stack spacing={3}>
                <Text fontSize="l">
                  I have experience with the software development life cycle and the best deveplopment practices
                  <br></br>
                  like unit testing, functional testing, integration testing, CI/CD from work and class experience.<br></br>
                </Text>
              </Stack>

              <Stack spacing={1}>
                <Text fontSize="l">
                  Programming languages: Java, Python, C, PHP.
                  <br></br>
                  Databases: MySQL, MongoDB.
                  <br></br>
                  Web development: ReactJS, NodeJS, ExpressJS, NextJS, Git/Github, Docker.
                  <br></br>
                  Other tools: Cypress, Travis CI, Heroku, Figma, Photoshop, WordPress.
                </Text>

              </Stack>

            </Stack>
          </Center>
        </div>

        {/* GET IN TOUCH SECTION */}
        <div className="section">
          {/* linear-gradient(240deg, #7C00E4, purple) purple */}

          <Box bg="linear-gradient(340deg, #7C00E4, pink)" maxHeight="2160px" h="100vh" color="white" id="contact">

            <Center maxHeight="2160px" h="95vh" color="white" id="contact">
              <Stack>
                <Heading as="h1" size="2xl">
                  Get In Touch
                </Heading>

                <HStack spacing={2} justifyContent="center" fontSize="xl">
                  <Link href="mailto:bbattur@calpoly.edu" isExternal> Email </Link>
                  <Link href="https://www.linkedin.com/in/bat-battur-a9b1b8217" isExternal> LinkedIn </Link>
                  <Link href="https://github.com/Baagi" isExternal> Github </Link>
                </HStack>
              </Stack>
            </Center>
            {/* <Footer justifyContent="center" /> */}
          </Box>
        </div>
      </main >

    </div >
  )
}
